[project]
name = "awbw-stats-aggregator"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pydantic>=2.12.4",
    "requests>=2.32.5",
]

[tool.ruff]
src = ["src"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "ruff>=0.14.4",
]

[tool.setuptools.packages.find]
where = ["src"]

